// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQNQY9zH4sxlZ5DSyEgzrmWPO8X_RNHc',
    appId: '1:1073157246114:web:c015578b2731a7bf525bfb',
    messagingSenderId: '1073157246114',
    projectId: 'booktracker-8149f',
    authDomain: 'booktracker-8149f.firebaseapp.com',
    storageBucket: 'booktracker-8149f.appspot.com',
    measurementId: 'G-2RET90EJJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfFzHNL4Hpkiy2rYrXXQIqK0P4FaYWHTc',
    appId: '1:1073157246114:android:8a9caf8f5017526c525bfb',
    messagingSenderId: '1073157246114',
    projectId: 'booktracker-8149f',
    storageBucket: 'booktracker-8149f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABaCtPZVyP8rS1tBL2JP_oJ0UUlw-zRjE',
    appId: '1:1073157246114:ios:27d1d00d8233d710525bfb',
    messagingSenderId: '1073157246114',
    projectId: 'booktracker-8149f',
    storageBucket: 'booktracker-8149f.appspot.com',
    iosClientId: '1073157246114-tr0nphi145kp8v2vv0s9jjqhi9kl8vog.apps.googleusercontent.com',
    iosBundleId: 'com.example.',
  );
}
